Repository deep-compute/gitkanban, pull requests merged in 2019-04, with the labels that each got.

#88 #51 implemented snooze feature
  gitkanban/gitkanban.py
Labels: review-status

#89 #51 moved global variables to config file
  gitkanban/gitkanban.py
Labels: review-status

#91 #51 implemented label logic
  gitkanban/gitkanban.py
Labels: inprogress-status

#94 #51 get snooze label from higher level of config file
  gitkanban/gitkanban.py
Labels: inprogress-status

#95 code bug.
  gitkanban/gitkanban.py
Labels: inprogress-status

#98 added assignees to alert message.
  gitkanban/gitkanban.py
Labels: inprogress-status

#101 #99 resolved escalation hierarchy bug
  gitkanban/constraints_state.py
  gitkanban/gitkanban.py
  setup.py
Labels: inprogress-status

#102 #97 handled snooze feature as per requested
  gitkanban/gitkanban.py
Labels: inprogress-status

#104 #38 implemented auto un-assign feature
  gitkanban/gitkanban.py
Labels: inprogress-status

#106 #85 implemented logic for not to consider weekends and non working hours for evaluating constraints
  gitkanban/gitkanban.py
  setup.py
Labels: inprogress-status

#108 #107 resolved new release bugs
  gitkanban/gitkanban.py
Labels: inprogress-status

#116 #114 resolved escalation hierarchy bug
  gitkanban/gitkanban.py
Labels: inprogress-status

#117 #109 implemented skip alerts on public holidays
  gitkanban/gitkanban.py
Labels: inprogress-status

#121 #118 resolved NoneType error in snooze feature
  gitkanban/gitkanban.py
Labels: inprogress-status

#123 #122 resolved snooze bug
  gitkanban/gitkanban.py
Labels: inprogress-status

#124 #115 resolved unassign people from auto un-assign feature
  gitkanban/gitkanban.py
Labels: inprogress-status

#128 #126 resolved snooze feature bug
  gitkanban/gitkanban.py
Labels: inprogress-status

#132 #126 removed duplicate repositories check for snooze feature
  gitkanban/gitkanban.py
Labels: inprogress-status

#137 #127 resolved escalation bug
  gitkanban/gitkanban.py
Labels: inprogress-status

#139 #138 handled connection error while requesting a url
  gitkanban/gitkanban.py
Labels: inprogress-status

#141 #130 implemented inbox logic
  gitkanban/gitkanban.py
Labels: inprogress-status

#143 #130 resolved inbox bug
  gitkanban/gitkanban.py
Labels: inprogress-status

#147 #129 send alert for agent assignees
  gitkanban/gitkanban.py
Labels: inprogress-status

#148 #146 stop sending alerts for snooze issues
  gitkanban/gitkanban.py
Labels: inprogress-status

#149 references #134, Removed .json extension check
  gitkanban/gitkanban.py
Labels: about-hour-effort, inprogress-status, low-impact, low-priority

#151 #113 implemented stop sending alerts during person off days
  gitkanban/gitkanban.py
Labels: inprogress-status

#153 #133 updated the example.conf file
  example.conf
Labels: inprogress-status

#154 #146 removed logic for snooze issues
  gitkanban/gitkanban.py
Labels: inprogress-status

#155 Custom work hours
  example.conf
  gitkanban/gitkanban.py
Labels: inprogress-status

#156 #110 implemented send alerts for freshers upto 1year
  gitkanban/gitkanban.py
Labels: inprogress-status

#157 #152 resolved inbox actual behaviour
  gitkanban/gitkanban.py
Labels: inprogress-status

#158 #152 resolved inbox bug
  gitkanban/gitkanban.py
Labels: inprogress-status

#160 #159 resolved pull request bug
  gitkanban/gitkanban.py
Labels: inprogress-status
